# Collision Avoidance - Live Demo

In this notebook we'll use the model we trained to detect whether the robot is ``free`` or ``blocked`` to enable a collision avoidance behavior on the robot.  

## Load the trained model

We'll assumed that you've already downloaded the ``best_model.pth`` to your workstation as instructed in the training notebook.  Now, you should upload this model into this notebook's
directory by using the Jupyter Lab upload tool.  Once that's finished there should be a file named ``best_model.pth`` in this notebook's directory.  

> Please make sure the file has uploaded fully before calling the next cell

Execute the code below to initialize the PyTorch model.  This should look very familiar from the training notebook.

# 請設定訓練完成後的模型檔(pth檔)名稱
## 請注意!
### 設定檔案名稱要記得指定副檔名為 --> .pth
### 設定檔案名稱要記得在名稱字串前後均加上引號 --> '

In [23]:
model_file = 'jetbot_CAVEDU/road_following/seangao_0525_v1_606.pth'

# 請設定馬達驅動板的規格
## 請確認Jetbot車上的馬達驅動板型號
### 若為DFRobot板則取消robot=Robot()前的 # 註解符號
### 若為Waveshare板則取消robot=Robot(driver_board = "waveshare")前的 # 註解符號

In [17]:
from jetbot import Robot

robot = Robot()
# robot = Robot(driver_board = "waveshare")

board begin success


# <font color="#dd0000">請注意!
# <font color="#dd0000">以下所有程式區塊內容，若非專業人士請勿任意修改程式碼。
# <font color="#dd0000">直接執行所有區塊即可。

## 設定功率模式到10W

In [18]:
import os
password = 'jetbot'
command_set_power = "sudo -S nvpmodel -m0"

print(command_set_power)

os.system('echo %s | %s'%(password,command_set_power))

sudo -S nvpmodel -m0


0

## 開啟散熱風扇

In [19]:
import os
password = 'jetbot'
command = "sudo -S sh -c 'echo 255 > /sys/devices/pwm-fan/target_pwm'"

print(command)

os.system('echo %s | %s'%(password,command))

sudo -S sh -c 'echo 255 > /sys/devices/pwm-fan/target_pwm'


0

In [20]:
import torch
import torchvision

model = torchvision.models.alexnet(pretrained=False)
model.classifier[6] = torch.nn.Linear(model.classifier[6].in_features, 2)

Next, load the trained weights from the ``best_model.pth`` file that you uploaded

In [24]:
model.load_state_dict(torch.load(model_file))

FileNotFoundError: [Errno 2] No such file or directory: 'jetbot_CAVEDU/road_following/seangao_0525_v1_606.pth'

Currently, the model weights are located on the CPU memory execute the code below to transfer to the GPU device.這邊載入需要一點時間

In [22]:
device = torch.device('cuda')
model = model.to(device)

### Create the preprocessing function

We have now loaded our model, but there's a slight issue.  The format that we trained our model doesnt *exactly* match the format of the camera.  To do that, 
we need to do some *preprocessing*.  This involves the following steps

1. Convert from BGR to RGB
2. Convert from HWC layout to CHW layout
3. Normalize using same parameters as we did during training (our camera provides values in [0, 255] range and training loaded images in [0, 1] range so we need to scale by 255.0
4. Transfer the data from CPU memory to GPU memory
5. Add a batch dimension

In [7]:
import cv2
import numpy as np

mean = 255.0 * np.array([0.485, 0.456, 0.406])
stdev = 255.0 * np.array([0.229, 0.224, 0.225])

normalize = torchvision.transforms.Normalize(mean, stdev)

def preprocess(camera_value):
    global device, normalize
    x = camera_value
    x = cv2.cvtColor(x, cv2.COLOR_BGR2RGB)
    x = x.transpose((2, 0, 1))
    x = torch.from_numpy(x).float()
    x = normalize(x)
    x = x.to(device)
    x = x[None, ...]
    return x

Great! We've now defined our pre-processing function which can convert images from the camera format to the neural network input format.

Now, let's start and display our camera.  You should be pretty familiar with this by now.  We'll also create a slider that will display the
probability that the robot is blocked.

In [ ]:
import traitlets
from IPython.display import display
import ipywidgets.widgets as widgets
from jetbot import Camera, bgr8_to_jpeg

camera = Camera.instance(width=224, height=224, fps=5)
image = widgets.Image(format='jpeg', width=224, height=224, fps=5)
blocked_slider = widgets.FloatSlider(description='blocked', min=0.0, max=1.0, orientation='vertical')

camera_link = traitlets.dlink((camera, 'value'), (image, 'value'), transform=bgr8_to_jpeg)

display(widgets.HBox([image, blocked_slider]))

We'll also create our robot instance which we'll need to drive the motors.

Next, we'll create a function that will get called whenever the camera's value changes.  This function will do the following steps

1. Pre-process the camera image
2. Execute the neural network
3. While the neural network output indicates we're blocked, we'll turn left, otherwise we go forward.

In [7]:
import torch.nn.functional as F
import time

def update(change):
    global blocked_slider, robot
    x = change['new'] 
    x = preprocess(x)
    y = model(x)
    
    # we apply the `softmax` function to normalize the output vector so it sums to 1 (which makes it a probability distribution)
    y = F.softmax(y, dim=1)
    
    prob_blocked = float(y.flatten()[0])
    prob_free = float(y.flatten()[1])
    
    blocked_slider.value = prob_blocked
    
    if prob_free > 0.5:
        robot.forward(0.4)
    else:
        robot.left(0.4)
    
    time.sleep(0.001)
        
update({'new': camera.value})  # we call the function once to intialize

NameError: name 'camera' is not defined

Cool! We've created our neural network execution function, but now we need to attach it to the camera for processing. 

We accomplish that with the ``observe`` function.

> WARNING: This code will move the robot!! Please make sure your robot has clearance.  The collision avoidance should work, but the neural
> network is only as good as the data it's trained on!

In [ ]:
camera.observe(update, names='value')  
#camera_link.unlink() 

Awesome! If your robot is plugged in it should now be generating new commands with each new camera frame.  Perhaps start by placing your robot on the ground and seeing what it does when it reaches an obstacle.

If you want to stop this behavior, you can unattach this callback by executing the code below.

# 請注意!
## 若確定要結束Jetbot的整體運作，再執行以下程式。

In [ ]:
camera.unobserve(update, names='value')
robot.stop()

Perhaps you want the robot to run without streaming video to the browser.  You can unlink the camera as below.

In [ ]:
camera_link.unlink()  # don't stream to browser (will still run camera)

# 請注意!
## 若需要關閉散熱風扇，在執行以下程式功能。
### 風扇關閉需要時間，會慢慢減速直到停止，請耐心等候。

In [ ]:
import os
password ='jetbot'
command = "sudo -S sh -c 'echo 0 > /sys/devices/pwm-fan/target_pwm'"

print(command)

os.system('echo %s | %s'%(password,command))

### Conclusion

That's it for this live demo!  Hopefully you had some fun and your robot avoided collisions intelligently! 

If your robot wasn't avoiding collisions very well, try to spot where it fails.  The beauty is that we can collect more data for these failure scenarios
and the robot should get even better :)